[package]
name = "andromeda"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = "5.2"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["a11y", "tokio", "winit", "wgpu", "xdg-portal", "about"]
